---
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: javawebappgreendeployment
    spec:
      replicas: 2
      strategy:
        type: RollingUpdate
      selector:
        matchLabels:
          app: java-web-app
          version: v2
          color: green
      template:
        metadata:
          name: javawebapppod
          labels:
            app: java-web-app
            version: v2
            color: green
        spec:
          containers:
          - name: javawebappcontainer
            image: ashokit/javawebapp:v2
            imagePullPolicy: Always
            ports:
            - containerPort: 8080
...
